services:

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ffreitas
            POSTGRES_PASSWORD: ffreitas
            POSTGRES_DB: book-reviews-db
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
