services:

    database:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: event_management_db
        ports:
            - "5432:5432"
        volumes:
            - postgres:/data/postgres
        restart: unless-stopped

volumes:
    postgres:
        driver: local

